### ISSUE TITLE
Video chat not working in iOS mobile browser

### ISSUE THREAD

**Issue by anantgarg** [cometchat-pro/javascript-chat-sdk#15]

**Comment by Ola-Bespoke** [comment]
Looking forward to this fix. Any ETA? :)

**Comment by ajaygajra** [comment]
@Ola-Bespoke issue has been fixed. please confirm.

**Comment by Ola-Bespoke** [comment]
That's great news, thank you! I'll update, test, then confirm tonight :)

**Comment by Ola-Bespoke** [comment]
@ajaygajra  I've updated to the latest and changed api calls from v1.6 to v1.8. 

Now can't login users because https://api.cometchat.com/v1.8/users/15/auth_tokens is returning 404 for newly created users. Any help with this?

As I can't login, I can't test video calls on mobile browsers.

**Comment by Ola-Bespoke** [comment]
Speaking to Ketan Yekale on Slack at the moment

**Comment by ajaygajra** [comment]
@Ola-Bespoke hope your issues are resolved?

**Comment by Ola-Bespoke** [comment]
Hi @ajaygajra , thanks for your help so far.

Ok, there's an improvement in that I no longer see that "download our app" screen on mobiles. 

However, video still can't be seen and audio can't be heard. It shows a warning message on the mobile screen about permissions but I checked my settings and mic and camera access have been granted to the browsers.

Desktop - Desktop audio and video sounds and displays fine.

Desktop - Mobile audio produces no sound on both desktop and mobile.

Desktop - Mobile video produces video on Desktop only, and no video on Mobile. For both, no audio sound is produced.

I tested this in the Safari and Firefox browsers on an iPhone 8 plus.

**Comment by Ola-Bespoke** [comment]
Hi @anantgarg @ajaygajra  Any response to the above?

**Comment by anantgarg** [comment]
Hi! We are still investigating this. These issues are primarily due to mobile browser level limitations. We’ll update this GitHub issue once we have a resolution. In the meanwhile, for better video experience, I’d recommend using our native SDKs.

**Comment by Rahul218691** [comment]
hi 
I tested the application on chrome which was working fine but on iPhone 6s safari browser I am not able to view anything it just renders me a white screen 
looking forward for solution or fixes.

**Comment by sithuwin123** [comment]
> @Ola-Bespoke issue has been fixed. please confirm.

any solution s ? i m using cometchat version 2.0.7 and in ios browser audio call and video call is not working .thz

**Comment by sithuwin123** [comment]
> @Ola-Bespoke issue has been fixed. please confirm.

can u tell me how u fix issue
