### ISSUE TITLE
The following error is coming when I am trying to end an ongoing call.

### ISSUE THREAD

**Issue by mayur-bhandari** [cometchat-pro/javascript-chat-sdk#38]
Uncaught TypeError: Cannot read property 'isCallstatsEnabled' of undefined Script: https://caesar.cometchat.com/libs/app.bundle.min.js?v=3387 Line: 60 Column: 227910 StackTrace:  TypeError: Cannot read property 'isCallstatsEnabled' of undefined

**Comment by mayur-bhandari** [comment]
This has been resolved in v1.8.13 and v2.0.0-beta8.

**Comment by caglarturkurka** [comment]
I think that this problem was not solved. I tried it with 1.8.13 and v2.0.0-beta8 version. But I got same error. 

I use the comet-chat/pro angular 7.x application
my package.json

```
{
  "name": "project-name",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve --port 5000",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e",
    "prod": "node --max_old_space_size=4096 ./node_modules/@angular/cli/bin/ng build --prod --build-optimizer",
    "customer": "ng build --configuration=customer",
    "compile:server": "webpack --config webpack.server.config.js --progress --colors",
    "serve:ssr": "node local.js",
    "build:ssr": "npm run build:client-and-server-bundles && npm run compile:server",
    "build:client-and-server-bundles": "node --max_old_space_size=4096 ./node_modules/@angular/cli/bin/ng build --prod && ng run project-name:server:production",
    "server": "node local.js",
    "build:prod": "npm run build:browser:prod && npm run build:server:prod",
    "serve:prerender": "node static.js",
    "build:prerender": "npm run build:prod && node dist/prerender.js",
    "build:browser:prod": "node --max_old_space_size=4096 ./node_modules/@angular/cli/bin/ng build --prod",
    "build:browser:serverless": "node --max_old_space_size=4096 ./node_modules/@angular/cli/bin/ng build --prod --base-href /production/",
    "build:serverless": "npm run build:browser:serverless && npm run build:server:serverless",
    "build:prod:deploy": "npm run build:prod && npm run deploy",
    "build:serverless:deploy": "npm run build:serverless && npm run deploy",
    "deploy": "serverless deploy",
    "build:server:prod": "ng run project-name:server && webpack --config webpack.server.config.js --progress --colors",
    "build:server:serverless": "ng run project-name:server:serverless && webpack --config webpack.server.config.js --progress --colors"
  },
  "private": true,
  "dependencies": {
    "@agm/core": "^1.0.0-beta.5",
    "@angular/animations": "^7.2.14",
    "@angular/cdk": "^7.3.7",
    "@angular/common": "~7.2.0",
    "@angular/compiler": "~7.2.0",
    "@angular/core": "~7.2.0",
    "@angular/forms": "~7.2.0",
    "@angular/http": "~7.2.0",
    "@angular/platform-browser": "~7.2.0",
    "@angular/platform-browser-dynamic": "~7.2.0",
    "@angular/platform-server": "~7.2.0",
    "@angular/router": "~7.2.0",
    "@cometchat-pro/chat": "^1.8.13",
    "@ng-bootstrap/ng-bootstrap": "^4.0.1",
    "@ng-select/ng-select": "^2.16.2",
    "@ng-toolkit/serverless": "^7.1.2",
    "@ng-toolkit/universal": "^7.1.2",
    "@nguniversal/common": "0.0.0",
    "@nguniversal/express-engine": "0.0.0",
    "@nguniversal/module-map-ngfactory-loader": "0.0.0",
    "@ngx-translate/core": "^11.0.1",
    "@ngx-translate/http-loader": "^4.0.0",
    "@swimlane/ngx-charts": "^10.1.0",
    "@swimlane/ngx-datatable": "^15.0.1",
    "@types/jquery": "^3.3.29",
    "angular2-google-maps": "^0.17.0",
    "aws-serverless-express": "^3.2.0",
    "babylonjs": "^3.3.0",
    "bootstrap": "^4.3.1",
    "classlist.js": "^1.1.20150312",
    "compass-mixins": "^0.12.10",
    "core-js": "^2.5.4",
    "cors": "~2.8.4",
    "cp-cli": "^1.1.0",
    "domino": "^2.1.3",
    "express": "^4.15.2",
    "font-awesome": "^4.7.0",
    "jquery": "^3.3.1",
    "mock-browser": "^0.92.14",
    "moment": "^2.24.0",
    "ng-jhipster": "^0.5.6",
    "ng-recaptcha": "^4.2.1",
    "ng2-file-upload": "^1.3.0",
    "ng2-search-filter": "^0.4.7",
    "ng2-truncate": "^1.3.17",
    "ng5-slider": "^1.2.4",
    "ngx-bootstrap": "^3.1.4",
    "ngx-cookie-service": "^2.1.0",
    "ngx-embed-video": "^1.0.4",
    "ngx-hm-carousel": "^1.6.5-bata.1",
    "ngx-image-cropper": "2.0.0",
    "ngx-lightbox": "^1.2.0",
    "ngx-loading": "^3.0.1",
    "ngx-socket-io": "^3.0.1",
    "ngx-validate-tooltip": "^1.0.3",
    "ngx-webstorage": "^3.0.0-beta.11",
    "ngx-xml2json": "^1.0.2",
    "rxjs": "~6.4.0",
    "sass": "^1.16.1",
    "socket.io-client": "^2.2.0",
    "terser": "3.14.1",
    "tslib": "^1.9.0",
    "utf-8-validate": "^5.0.2",
    "web-animations-js": "^2.3.2",
    "zone.js": "~0.9.1"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.12.0",
    "@angular/cli": "~7.2.1",
    "@angular/compiler-cli": "~7.2.0",
    "@angular/language-service": "~7.2.0",
    "@types/node": "~8.9.4",
    "@types/jasmine": "~2.8.8",
    "@types/jasminewd2": "~2.0.3",
    "codelyzer": "~4.5.0",
    "jasmine-core": "~2.99.1",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~3.1.1",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~1.1.2",
    "karma-jasmine-html-reporter": "^0.2.2",
    "opencollective": "^1.0.3",
    "protractor": "~5.4.0",
    "serverless": "1.40.0",
    "serverless-apigw-binary": "^0.4.4",
    "ts-loader": "^5.2.0",
    "ts-node": "~7.0.0",
    "tslint": "~5.15.0",
    "typescript": "~3.2.2",
    "webpack-cli": "^3.1.0"
  },
  "resolutions": {
    "terser": "3.14.1"
  }
}
```
